# Generated by Django 5.2.1 on 2025-05-14 13:43

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['reminder_date', 'reminder_time']},
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_datetime',
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
